# Generated by Django 5.2.11 on 2026-02-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('health', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned'), ('onboard', 'Onboarding'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('assigned', models.CharField(blank=True, default='', max_length=255)),
                ('since', models.DateField(auto_now_add=True)),
                ('converted_from_lead', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-since'],
            },
        ),
    ]
